function [ events ] = loadEventsFile( filename, events_to_skip )
%LOADEVENTSFILE loads the event file generated by the manager
EVENT_MOVE= 1;
events = {};
fid = fopen(filename, 'r');
tline = fgetl(fid);
i=1;
while ischar(tline)
    %disp(tline)

    %6740 Event 51157 1 VehicleMoved 
    format_spec = '%d %s %f %d %s %s %s %f %f %f %f';
    C = textscan(tline, format_spec);
    %[id, ~, et, etype, ~, ~, entities, ext1, ext2, ext3, ext4]
    e = struct();
    e.t = C{1};
    e.id = C{3};
    e.type = C{4};
    
    if any(e.type == events_to_skip) 
        % skip this entry and move to next line
        tline = fgetl(fid);
        continue;
    end
    
    e.entities = cell2mat(textscan(char(C{7}), '%d', 'delimiter', ','));
    if (e.type == 5 || e.type == 6) 
        e.size = C{8};
        e.pos = [C{9} C{10}];
    else 
        e.pos = [C{8} C{9}];
    end
    
    if (mod(i, 10000) == 0) 
        fprintf('Loaded t <= %f\n', e.t);
    end
    
    events{i} = e;
    tline = fgetl(fid);
    i = i + 1;
end